SP_500_CONFIG = [
	{"symbol": "AAPL", "name": "Apple Inc."},
	# {"symbol": "NVDA", "name": "NVIDIA Corporation"},
	# {"symbol": "MSFT", "name": "Microsoft Corporation"},
	# {"symbol": "AMZN", "name": "Amazon.com, Inc."},
	# {"symbol": "GOOGL", "name": "Alphabet Inc."},
	# {"symbol": "GOOG", "name": "Alphabet Inc."},
	# {"symbol": "META", "name": "Meta Platforms, Inc."},
	# {"symbol": "TSLA", "name": "Tesla, Inc."},
	# {"symbol": "AVGO", "name": "Broadcom Inc."},
	# {"symbol": "BRK-B", "name": "Berkshire Hathaway Inc. New"},
	# {"symbol": "WMT", "name": "Walmart Inc."},
	# {"symbol": "LLY", "name": "Eli Lilly and Company"},
	# {"symbol": "JPM", "name": "JP Morgan Chase & Co."},
	# {"symbol": "V", "name": "Visa Inc."},
	# {"symbol": "MA", "name": "Mastercard Incorporated"},
	# {"symbol": "ORCL", "name": "Oracle Corporation"},
	# {"symbol": "XOM", "name": "Exxon Mobil Corporation"},
	# {"symbol": "UNH", "name": "UnitedHealth Group Incorporated"},
	# {"symbol": "COST", "name": "Costco Wholesale Corporation"},
	# {"symbol": "PG", "name": "Procter & Gamble Company (The)"},
	# {"symbol": "HD", "name": "Home Depot, Inc. (The)"},
	# {"symbol": "NFLX", "name": "Netflix, Inc."},
	# {"symbol": "JNJ", "name": "Johnson & Johnson"},
	# {"symbol": "BAC", "name": "Bank of America Corporation"},
	# {"symbol": "CRM", "name": "Salesforce, Inc."},
	# {"symbol": "ABBV", "name": "AbbVie Inc."},
	# {"symbol": "KO", "name": "Coca-Cola Company (The)"},
	# {"symbol": "TMUS", "name": "T-Mobile US, Inc."},
	# {"symbol": "CVX", "name": "Chevron Corporation"},
	# {"symbol": "MRK", "name": "Merck & Company, Inc."},
	# {"symbol": "WFC", "name": "Wells Fargo & Company"},
	# {"symbol": "CSCO", "name": "Cisco Systems, Inc."},
	# {"symbol": "ACN", "name": "Accenture plc"},
	# {"symbol": "NOW", "name": "ServiceNow, Inc."},
	# {"symbol": "AXP", "name": "American Express Company"},
	# {"symbol": "MCD", "name": "McDonald's Corporation"},
	# {"symbol": "PEP", "name": "Pepsico, Inc."},
	# {"symbol": "BX", "name": "Blackstone Inc."},
	# {"symbol": "IBM", "name": "International Business Machines"},
	# {"symbol": "DIS", "name": "Walt Disney Company (The)"},
	# {"symbol": "LIN", "name": "Linde plc"},
	# {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc"},
	# {"symbol": "MS", "name": "Morgan Stanley"},
	# {"symbol": "ABT", "name": "Abbott Laboratories"},
	# {"symbol": "ADBE", "name": "Adobe Inc."},
	# {"symbol": "AMD", "name": "Advanced Micro Devices, Inc."},
	# {"symbol": "PM", "name": "Philip Morris International Inc"},
	# {"symbol": "ISRG", "name": "Intuitive Surgical, Inc."},
	# {"symbol": "PLTR", "name": "Palantir Technologies Inc."},
	# {"symbol": "GE", "name": "GE Aerospace"},
	# {"symbol": "INTU", "name": "Intuit Inc."},
	# {"symbol": "GS", "name": "Goldman Sachs Group, Inc. (The)"},
	# {"symbol": "CAT", "name": "Caterpillar, Inc."},
	# {"symbol": "TXN", "name": "Texas Instruments Incorporated"},
	# {"symbol": "QCOM", "name": "QUALCOMM Incorporated"},
	# {"symbol": "VZ", "name": "Verizon Communications Inc."},
	# {"symbol": "BKNG", "name": "Booking Holdings Inc. Common St"},
	# {"symbol": "DHR", "name": "Danaher Corporation"},
	# {"symbol": "T", "name": "AT&T Inc."},
	# {"symbol": "BLK", "name": "BlackRock, Inc."},
	# {"symbol": "RTX", "name": "RTX Corporation"},
	# {"symbol": "SPGI", "name": "S&P Global Inc."},
	# {"symbol": "PFE", "name": "Pfizer, Inc."},
	# {"symbol": "HON", "name": "Honeywell International Inc."},
	# {"symbol": "NEE", "name": "NextEra Energy, Inc."},
	# {"symbol": "CMCSA", "name": "Comcast Corporation"},
	# {"symbol": "ANET", "name": "Arista Networks, Inc."},
	# {"symbol": "AMGN", "name": "Amgen Inc."},
	# {"symbol": "PGR", "name": "Progressive Corporation (The)"},
	# {"symbol": "LOW", "name": "Lowe's Companies, Inc."},
	# {"symbol": "SYK", "name": "Stryker Corporation"},
	# {"symbol": "UNP", "name": "Union Pacific Corporation"},
	# {"symbol": "TJX", "name": "TJX Companies, Inc. (The)"},
	# {"symbol": "KKR", "name": "KKR & Co. Inc."},
	# {"symbol": "SCHW", "name": "Charles Schwab Corporation (The"},
	# {"symbol": "ETN", "name": "Eaton Corporation, PLC"},
	# {"symbol": "AMAT", "name": "Applied Materials, Inc."},
	# {"symbol": "BA", "name": "Boeing Company (The)"},
	# {"symbol": "BSX", "name": "Boston Scientific Corporation"},
	# {"symbol": "C", "name": "Citigroup, Inc."},
	# {"symbol": "UBER", "name": "Uber Technologies, Inc."},
	# {"symbol": "COP", "name": "ConocoPhillips"},
	# {"symbol": "PANW", "name": "Palo Alto Networks, Inc."},
	# {"symbol": "ADP", "name": "Automatic Data Processing, Inc."},
	# {"symbol": "DE", "name": "Deere & Company"},
	# {"symbol": "FI", "name": "Fiserv, Inc."},
	# {"symbol": "BMY", "name": "Bristol-Myers Squibb Company"},
	# {"symbol": "LMT", "name": "Lockheed Martin Corporation"},
	# {"symbol": "GILD", "name": "Gilead Sciences, Inc."},
	# {"symbol": "NKE", "name": "Nike, Inc."},
	# {"symbol": "CB", "name": "Chubb Limited"},
	# {"symbol": "UPS", "name": "United Parcel Service, Inc."},
	# {"symbol": "ADI", "name": "Analog Devices, Inc."},
	# {"symbol": "MMC", "name": "Marsh & McLennan Companies, Inc"},
	# {"symbol": "MDT", "name": "Medtronic plc."},
	# {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Incorpor"},
	# {"symbol": "MU", "name": "Micron Technology, Inc."},
	# {"symbol": "SBUX", "name": "Starbucks Corporation"},
	# {"symbol": "PLD", "name": "Prologis, Inc."},
	# {"symbol": "GEV", "name": "GE Vernova Inc."},
	# {"symbol": "LRCX", "name": "Lam Research Corporation"},
	# {"symbol": "MO", "name": "Altria Group, Inc."},
	# {"symbol": "SO", "name": "Southern Company (The)"},
	# {"symbol": "EQIX", "name": "Equinix, Inc."},
	# {"symbol": "CRWD", "name": "CrowdStrike Holdings, Inc."},
	# {"symbol": "PYPL", "name": "PayPal Holdings, Inc."},
	# {"symbol": "SHW", "name": "Sherwin-Williams Company (The)"},
	# {"symbol": "ICE", "name": "Intercontinental Exchange Inc."},
	# {"symbol": "CME", "name": "CME Group Inc."},
	# {"symbol": "AMT", "name": "American Tower Corporation (REI"},
	# {"symbol": "APH", "name": "Amphenol Corporation"},
	# {"symbol": "ELV", "name": "Elevance Health, Inc."},
	# {"symbol": "TT", "name": "Trane Technologies plc"},
	# {"symbol": "MCO", "name": "Moody's Corporation"},
	# {"symbol": "CMG", "name": "Chipotle Mexican Grill, Inc."},
	# {"symbol": "INTC", "name": "Intel Corporation"},
	# {"symbol": "KLAC", "name": "KLA Corporation"},
	# {"symbol": "ABNB", "name": "Airbnb, Inc."},
	# {"symbol": "DUK", "name": "Duke Energy Corporation (Holdin"},
	# {"symbol": "PH", "name": "Parker-Hannifin Corporation"},
	# {"symbol": "CDNS", "name": "Cadence Design Systems, Inc."},
	# {"symbol": "WM", "name": "Waste Management, Inc."},
	# {"symbol": "DELL", "name": "Dell Technologies Inc."},
	# {"symbol": "MDLZ", "name": "Mondelez International, Inc."},
	# {"symbol": "MAR", "name": "Marriott International"},
	# {"symbol": "MSI", "name": "Motorola Solutions, Inc."},
	# {"symbol": "WELL", "name": "Welltower Inc."},
	# {"symbol": "AON", "name": "Aon plc"},
	# {"symbol": "REGN", "name": "Regeneron Pharmaceuticals, Inc."},
	# {"symbol": "CI", "name": "The Cigna Group"},
	# {"symbol": "HCA", "name": "HCA Healthcare, Inc."},
	# {"symbol": "PNC", "name": "PNC Financial Services Group, I"},
	# {"symbol": "ITW", "name": "Illinois Tool Works Inc."},
	# {"symbol": "SNPS", "name": "Synopsys, Inc."},
	# {"symbol": "CTAS", "name": "Cintas Corporation"},
	# {"symbol": "CL", "name": "Colgate-Palmolive Company"},
	# {"symbol": "USB", "name": "U.S. Bancorp"},
	# {"symbol": "FTNT", "name": "Fortinet, Inc."},
	# {"symbol": "ZTS", "name": "Zoetis Inc."},
	# {"symbol": "MCK", "name": "McKesson Corporation"},
	# {"symbol": "GD", "name": "General Dynamics Corporation"},
	# {"symbol": "TDG", "name": "Transdigm Group Incorporated"},
	# {"symbol": "CEG", "name": "Constellation Energy Corporatio"},
	# {"symbol": "AJG", "name": "Arthur J. Gallagher & Co."},
	# {"symbol": "EMR", "name": "Emerson Electric Company"},
	# {"symbol": "MMM", "name": "3M Company"},
	# {"symbol": "ORLY", "name": "O'Reilly Automotive, Inc."},
	# {"symbol": "NOC", "name": "Northrop Grumman Corporation"},
	# {"symbol": "COF", "name": "Capital One Financial Corporati"},
	# {"symbol": "ECL", "name": "Ecolab Inc."},
	# {"symbol": "EOG", "name": "EOG Resources, Inc."},
	# {"symbol": "FDX", "name": "FedEx Corporation"},
	# {"symbol": "BDX", "name": "Becton, Dickinson and Company"},
	# {"symbol": "APD", "name": "Air Products and Chemicals, Inc"},
	# {"symbol": "WMB", "name": "Williams Companies, Inc. (The)"},
	# {"symbol": "SPG", "name": "Simon Property Group, Inc."},
	# {"symbol": "ADSK", "name": "Autodesk, Inc."},
	# {"symbol": "RCL", "name": "Royal Caribbean Cruises Ltd."},
	# {"symbol": "RSG", "name": "Republic Services, Inc."},
	# {"symbol": "CARR", "name": "Carrier Global Corporation"},
	# {"symbol": "CSX", "name": "CSX Corporation"},
	# {"symbol": "HLT", "name": "Hilton Worldwide Holdings Inc."},
	# {"symbol": "DLR", "name": "Digital Realty Trust, Inc."},
	# {"symbol": "TGT", "name": "Target Corporation"},
	# {"symbol": "KMI", "name": "Kinder Morgan, Inc."},
	# {"symbol": "OKE", "name": "ONEOK, Inc."},
	# {"symbol": "TFC", "name": "Truist Financial Corporation"},
	# {"symbol": "AFL", "name": "AFLAC Incorporated"},
	# {"symbol": "GM", "name": "General Motors Company"},
	# {"symbol": "BK", "name": "The Bank of New York Mellon Cor"},
	# {"symbol": "ROP", "name": "Roper Technologies, Inc."},
	# {"symbol": "MET", "name": "MetLife, Inc."},
	# {"symbol": "CPRT", "name": "Copart, Inc."},
	# {"symbol": "FCX", "name": "Freeport-McMoRan, Inc."},
	# {"symbol": "CVS", "name": "CVS Health Corporation"},
	# {"symbol": "PCAR", "name": "PACCAR Inc."},
	# {"symbol": "SRE", "name": "DBA Sempra"},
	# {"symbol": "AZO", "name": "AutoZone, Inc."},
	# {"symbol": "TRV", "name": "The Travelers Companies, Inc."},
	# {"symbol": "NXPI", "name": "NXP Semiconductors N.V."},
	# {"symbol": "JCI", "name": "Johnson Controls International "},
	# {"symbol": "GWW", "name": "W.W. Grainger, Inc."},
	# {"symbol": "NSC", "name": "Norfolk Southern Corporation"},
	# {"symbol": "PSA", "name": "Public Storage"},
	# {"symbol": "SLB", "name": "Schlumberger N.V."},
	# {"symbol": "AMP", "name": "Ameriprise Financial, Inc."},
	# {"symbol": "ALL", "name": "Allstate Corporation (The)"},
	# {"symbol": "FICO", "name": "Fair Isaac Corporation"},
	# {"symbol": "MNST", "name": "Monster Beverage Corporation"},
	# {"symbol": "PAYX", "name": "Paychex, Inc."},
	# {"symbol": "CHTR", "name": "Charter Communications, Inc."},
	# {"symbol": "AEP", "name": "American Electric Power Company"},
	# {"symbol": "ROST", "name": "Ross Stores, Inc."},
	# {"symbol": "PWR", "name": "Quanta Services, Inc."},
	# {"symbol": "CMI", "name": "Cummins Inc."},
	# {"symbol": "AXON", "name": "Axon Enterprise, Inc."},
	# {"symbol": "VST", "name": "Vistra Corp."},
	# {"symbol": "URI", "name": "United Rentals, Inc."},
	# {"symbol": "MSCI", "name": "MSCI Inc."},
	# {"symbol": "LULU", "name": "lululemon athletica inc."},
	# {"symbol": "O", "name": "Realty Income Corporation"},
	# {"symbol": "PSX", "name": "Phillips 66"},
	# {"symbol": "AIG", "name": "American International Group, I"},
	# {"symbol": "FANG", "name": "Diamondback Energy, Inc."},
	# {"symbol": "D", "name": "Dominion Energy, Inc."},
	# {"symbol": "HWM", "name": "Howmet Aerospace Inc."},
	# {"symbol": "DHI", "name": "D.R. Horton, Inc."},
	# {"symbol": "KR", "name": "Kroger Company (The)"},
	# {"symbol": "NDAQ", "name": "Nasdaq, Inc."},
	# {"symbol": "OXY", "name": "Occidental Petroleum Corporatio"},
	# {"symbol": "EW", "name": "Edwards Lifesciences Corporatio"},
	# {"symbol": "COR", "name": "Cencora, Inc."},
	# {"symbol": "KDP", "name": "Keurig Dr Pepper Inc."},
	# {"symbol": "FIS", "name": "Fidelity National Information S"},
	# {"symbol": "KMB", "name": "Kimberly-Clark Corporation"},
	# {"symbol": "NEM", "name": "Newmont Corporation"},
	# {"symbol": "DFS", "name": "Discover Financial Services"},
	# {"symbol": "PCG", "name": "Pacific Gas & Electric Co."},
	# {"symbol": "TEL", "name": "TE Connectivity plc"},
	# {"symbol": "MPC", "name": "Marathon Petroleum Corporation"},
	# {"symbol": "FAST", "name": "Fastenal Company"},
	# {"symbol": "AME", "name": "AMETEK, Inc."},
	# {"symbol": "PEG", "name": "Public Service Enterprise Group"},
	# {"symbol": "PRU", "name": "Prudential Financial, Inc."},
	# {"symbol": "KVUE", "name": "Kenvue Inc."},
	# {"symbol": "STZ", "name": "Constellation Brands, Inc."},
	# {"symbol": "GLW", "name": "Corning Incorporated"},
	# {"symbol": "LHX", "name": "L3Harris Technologies, Inc."},
	# {"symbol": "GRMN", "name": "Garmin Ltd."},
	# {"symbol": "BKR", "name": "Baker Hughes Company"},
	# {"symbol": "CBRE", "name": "CBRE Group Inc"},
	# {"symbol": "CTVA", "name": "Corteva, Inc."},
	# {"symbol": "HES", "name": "Hess Corporation"},
	# {"symbol": "CCI", "name": "Crown Castle Inc."},
	# {"symbol": "DAL", "name": "Delta Air Lines, Inc."},
	# {"symbol": "CTSH", "name": "Cognizant Technology Solutions "},
	# {"symbol": "F", "name": "Ford Motor Company"},
	# {"symbol": "VRSK", "name": "Verisk Analytics, Inc."},
	# {"symbol": "EA", "name": "Electronic Arts Inc."},
	# {"symbol": "ODFL", "name": "Old Dominion Freight Line, Inc."},
	# {"symbol": "XEL", "name": "Xcel Energy Inc."},
	# {"symbol": "TRGP", "name": "Targa Resources, Inc."},
	# {"symbol": "A", "name": "Agilent Technologies, Inc."},
	# {"symbol": "IT", "name": "Gartner, Inc."},
	# {"symbol": "LVS", "name": "Las Vegas Sands Corp."},
	# {"symbol": "SYY", "name": "Sysco Corporation"},
	# {"symbol": "VLO", "name": "Valero Energy Corporation"},
	# {"symbol": "OTIS", "name": "Otis Worldwide Corporation"},
	# {"symbol": "LEN", "name": "Lennar Corporation"},
	# {"symbol": "EXC", "name": "Exelon Corporation"},
	# {"symbol": "IR", "name": "Ingersoll Rand Inc."},
	# {"symbol": "YUM", "name": "Yum! Brands, Inc."},
	# {"symbol": "KHC", "name": "The Kraft Heinz Company"},
	# {"symbol": "GEHC", "name": "GE HealthCare Technologies Inc."},
	# {"symbol": "IQV", "name": "IQVIA Holdings, Inc."},
	# {"symbol": "GIS", "name": "General Mills, Inc."},
	# {"symbol": "CCL", "name": "Carnival Corporation"},
	# {"symbol": "RMD", "name": "ResMed Inc."},
	# {"symbol": "VMC", "name": "Vulcan Materials Company (Holdi"},
	# {"symbol": "HSY", "name": "The Hershey Company"},
	# {"symbol": "ACGL", "name": "Arch Capital Group Ltd."},
	# {"symbol": "IDXX", "name": "IDEXX Laboratories, Inc."},
	# {"symbol": "WAB", "name": "Westinghouse Air Brake Technolo"},
	# {"symbol": "ROK", "name": "Rockwell Automation, Inc."},
	# {"symbol": "MLM", "name": "Martin Marietta Materials, Inc."},
	# {"symbol": "EXR", "name": "Extra Space Storage Inc"},
	# {"symbol": "DD", "name": "DuPont de Nemours, Inc."},
	# {"symbol": "ETR", "name": "Entergy Corporation"},
	# {"symbol": "DECK", "name": "Deckers Outdoor Corporation"},
	# {"symbol": "EFX", "name": "Equifax, Inc."},
	# {"symbol": "UAL", "name": "United Airlines Holdings, Inc."},
	# {"symbol": "WTW", "name": "Willis Towers Watson Public Lim"},
	# {"symbol": "TTWO", "name": "Take-Two Interactive Software, "},
	# {"symbol": "HIG", "name": "Hartford Financial Services Gro"},
	# {"symbol": "RJF", "name": "Raymond James Financial, Inc."},
	# {"symbol": "AVB", "name": "AvalonBay Communities, Inc."},
	# {"symbol": "MTB", "name": "M&T Bank Corporation"},
	# {"symbol": "DXCM", "name": "DexCom, Inc."},
	# {"symbol": "ED", "name": "Consolidated Edison, Inc."},
	# {"symbol": "EBAY", "name": "eBay Inc."},
	# {"symbol": "HPQ", "name": "HP Inc."},
	# {"symbol": "IRM", "name": "Iron Mountain Incorporated (Del"},
	# {"symbol": "EIX", "name": "Edison International"},
	# {"symbol": "LYV", "name": "Live Nation Entertainment, Inc."},
	# {"symbol": "VICI", "name": "VICI Properties Inc."},
	# {"symbol": "CNC", "name": "Centene Corporation"},
	# {"symbol": "WEC", "name": "WEC Energy Group, Inc."},
	# {"symbol": "MCHP", "name": "Microchip Technology Incorporat"},
	# {"symbol": "HUM", "name": "Humana Inc."},
	# {"symbol": "ANSS", "name": "ANSYS, Inc."},
	# {"symbol": "BRO", "name": "Brown & Brown, Inc."},
	# {"symbol": "CSGP", "name": "CoStar Group, Inc."},
	# {"symbol": "MPWR", "name": "Monolithic Power Systems, Inc."},
	# {"symbol": "GDDY", "name": "GoDaddy Inc."},
	# {"symbol": "TSCO", "name": "Tractor Supply Company"},
	# {"symbol": "STT", "name": "State Street Corporation"},
	# {"symbol": "CAH", "name": "Cardinal Health, Inc."},
	# {"symbol": "GPN", "name": "Global Payments Inc."},
	# {"symbol": "FITB", "name": "Fifth Third Bancorp"},
	# {"symbol": "XYL", "name": "Xylem Inc."},
	# {"symbol": "HPE", "name": "Hewlett Packard Enterprise Comp"},
	# {"symbol": "KEYS", "name": "Keysight Technologies Inc."},
	# {"symbol": "DOW", "name": "Dow Inc."},
	# {"symbol": "EQR", "name": "Equity Residential"},
	# {"symbol": "ON", "name": "ON Semiconductor Corporation"},
	# {"symbol": "PPG", "name": "PPG Industries, Inc."},
	# {"symbol": "K", "name": "Kellanova"},
	# {"symbol": "SW", "name": "Smurfit WestRock plc"},
	# {"symbol": "NUE", "name": "Nucor Corporation"},
	# {"symbol": "EL", "name": "Estee Lauder Companies, Inc. (T"},
	# {"symbol": "BR", "name": "Broadridge Financial Solutions,"},
	# {"symbol": "WBD", "name": "Warner Bros. Discovery, Inc. - "},
	# {"symbol": "TPL", "name": "Texas Pacific Land Corporation"},
	# {"symbol": "CHD", "name": "Church & Dwight Company, Inc."},
	# {"symbol": "MTD", "name": "Mettler-Toledo International, I"},
	# {"symbol": "DOV", "name": "Dover Corporation"},
	# {"symbol": "TYL", "name": "Tyler Technologies, Inc."},
	# {"symbol": "FTV", "name": "Fortive Corporation"},
	# {"symbol": "TROW", "name": "T. Rowe Price Group, Inc."},
	# {"symbol": "VLTO", "name": "Veralto Corp"},
	# {"symbol": "EQT", "name": "EQT Corporation"},
	# {"symbol": "SYF", "name": "Synchrony Financial"},
	# {"symbol": "NVR", "name": "NVR, Inc."},
	# {"symbol": "DTE", "name": "DTE Energy Company"},
	# {"symbol": "VTR", "name": "Ventas, Inc."},
	# {"symbol": "AWK", "name": "American Water Works Company, I"},
	# {"symbol": "ADM", "name": "Archer-Daniels-Midland Company"},
	# {"symbol": "NTAP", "name": "NetApp, Inc."},
	# {"symbol": "WST", "name": "West Pharmaceutical Services, I"},
	# {"symbol": "CPAY", "name": "Corpay, Inc."},
	# {"symbol": "PPL", "name": "PPL Corporation"},
	# {"symbol": "LYB", "name": "LyondellBasell Industries NV"},
	# {"symbol": "AEE", "name": "Ameren Corporation"},
	# {"symbol": "EXPE", "name": "Expedia Group, Inc."},
	# {"symbol": "HBAN", "name": "Huntington Bancshares Incorpora"},
	# {"symbol": "CDW", "name": "CDW Corporation"},
	# {"symbol": "FE", "name": "FirstEnergy Corp."},
	# {"symbol": "HUBB", "name": "Hubbell Inc"},
	# {"symbol": "HAL", "name": "Halliburton Company"},
	# {"symbol": "ROL", "name": "Rollins, Inc."},
	# {"symbol": "PHM", "name": "PulteGroup, Inc."},
	# {"symbol": "CINF", "name": "Cincinnati Financial Corporatio"},
	# {"symbol": "PTC", "name": "PTC Inc."},
	# {"symbol": "WRB", "name": "W.R. Berkley Corporation"},
	# {"symbol": "DRI", "name": "Darden Restaurants, Inc."},
	# {"symbol": "FOXA", "name": "Fox Corporation"},
	# {"symbol": "FOX", "name": "Fox Corporation"},
	# {"symbol": "IFF", "name": "International Flavors & Fragran"},
	# {"symbol": "SBAC", "name": "SBA Communications Corporation"},
	# {"symbol": "WAT", "name": "Waters Corporation"},
	# {"symbol": "ERIE", "name": "Erie Indemnity Company"},
	# {"symbol": "TDY", "name": "Teledyne Technologies Incorpora"},
	# {"symbol": "ATO", "name": "Atmos Energy Corporation"},
	# {"symbol": "RF", "name": "Regions Financial Corporation"},
	# {"symbol": "BIIB", "name": "Biogen Inc."},
	# {"symbol": "ZBH", "name": "Zimmer Biomet Holdings, Inc."},
	# {"symbol": "CNP", "name": "CenterPoint Energy, Inc (Holdin"},
	# {"symbol": "MKC", "name": "McCormick & Company, Incorporat"},
	# {"symbol": "ES", "name": "Eversource Energy (D/B/A)"},
	# {"symbol": "WDC", "name": "Western Digital Corporation"},
	# {"symbol": "TSN", "name": "Tyson Foods, Inc."},
	# {"symbol": "TER", "name": "Teradyne, Inc."},
	# {"symbol": "STE", "name": "STERIS plc (Ireland)"},
	# {"symbol": "PKG", "name": "Packaging Corporation of Americ"},
	# {"symbol": "CLX", "name": "Clorox Company (The)"},
	# {"symbol": "NTRS", "name": "Northern Trust Corporation"},
	# {"symbol": "ZBRA", "name": "Zebra Technologies Corporation"},
	# {"symbol": "DVN", "name": "Devon Energy Corporation"},
	# {"symbol": "CBOE", "name": "Cboe Global Markets, Inc."},
	# {"symbol": "WY", "name": "Weyerhaeuser Company"},
	# {"symbol": "LUV", "name": "Southwest Airlines Company"},
	# {"symbol": "ULTA", "name": "Ulta Beauty, Inc."},
	# {"symbol": "CMS", "name": "CMS Energy Corporation"},
	# {"symbol": "INVH", "name": "Invitation Homes Inc."},
	# {"symbol": "FSLR", "name": "First Solar, Inc."},
	# {"symbol": "BF-B", "name": "Brown Forman Inc"},
	# {"symbol": "LDOS", "name": "Leidos Holdings, Inc."},
	# {"symbol": "CFG", "name": "Citizens Financial Group, Inc."},
	# {"symbol": "LH", "name": "Labcorp Holdings Inc."},
	# {"symbol": "VRSN", "name": "VeriSign, Inc."},
	# {"symbol": "IP", "name": "International Paper Company"},
	# {"symbol": "ESS", "name": "Essex Property Trust, Inc."},
	# {"symbol": "PODD", "name": "Insulet Corporation"},
	# {"symbol": "COO", "name": "The Cooper Companies, Inc."},
	# {"symbol": "SMCI", "name": "Super Micro Computer, Inc."},
	# {"symbol": "STX", "name": "Seagate Technology Holdings PLC"},
	# {"symbol": "MAA", "name": "Mid-America Apartment Communiti"},
	# {"symbol": "FDS", "name": "FactSet Research Systems Inc."},
	# {"symbol": "NRG", "name": "NRG Energy, Inc."},
	# {"symbol": "BBY", "name": "Best Buy Co., Inc."},
	# {"symbol": "SNA", "name": "Snap-On Incorporated"},
	# {"symbol": "L", "name": "Loews Corporation"},
	# {"symbol": "PFG", "name": "Principal Financial Group Inc"},
	# {"symbol": "STLD", "name": "Steel Dynamics, Inc."},
	# {"symbol": "TRMB", "name": "Trimble Inc."},
	# {"symbol": "OMC", "name": "Omnicom Group Inc."},
	# {"symbol": "CTRA", "name": "Coterra Energy Inc."},
	# {"symbol": "HRL", "name": "Hormel Foods Corporation"},
	# {"symbol": "ARE", "name": "Alexandria Real Estate Equities"},
	# {"symbol": "BLDR", "name": "Builders FirstSource, Inc."},
	# {"symbol": "JBHT", "name": "J.B. Hunt Transport Services, I"},
	# {"symbol": "GEN", "name": "Gen Digital Inc."},
	# {"symbol": "DGX", "name": "Quest Diagnostics Incorporated"},
	# {"symbol": "KEY", "name": "KeyCorp"},
	# {"symbol": "NI", "name": "NiSource Inc"},
	# {"symbol": "MOH", "name": "Molina Healthcare Inc"},
	# {"symbol": "PNR", "name": "Pentair plc."},
	# {"symbol": "J", "name": "Jacobs Solutions Inc."},
	# {"symbol": "DG", "name": "Dollar General Corporation"},
	# {"symbol": "BALL", "name": "Ball Corporation"},
	# {"symbol": "NWS", "name": "News Corporation"},
	# {"symbol": "NWSA", "name": "News Corporation"},
	# {"symbol": "UDR", "name": "UDR, Inc."},
	# {"symbol": "HOLX", "name": "Hologic, Inc."},
	# {"symbol": "JBL", "name": "Jabil Inc."},
	# {"symbol": "GPC", "name": "Genuine Parts Company"},
	# {"symbol": "IEX", "name": "IDEX Corporation"},
	# {"symbol": "MAS", "name": "Masco Corporation"},
	# {"symbol": "KIM", "name": "Kimco Realty Corporation (HC)"},
	# {"symbol": "ALGN", "name": "Align Technology, Inc."},
	# {"symbol": "DLTR", "name": "Dollar Tree, Inc."},
	# {"symbol": "EXPD", "name": "Expeditors International of Was"},
	# {"symbol": "EG", "name": "Everest Group, Ltd."},
	# {"symbol": "MRNA", "name": "Moderna, Inc."},
	# {"symbol": "LNT", "name": "Alliant Energy Corporation"},
	# {"symbol": "AVY", "name": "Avery Dennison Corporation"},
	# {"symbol": "BAX", "name": "Baxter International Inc."},
	# {"symbol": "TPR", "name": "Tapestry, Inc."},
	# {"symbol": "VTRS", "name": "Viatris Inc."},
	# {"symbol": "CF", "name": "CF Industries Holdings, Inc."},
	# {"symbol": "FFIV", "name": "F5, Inc."},
	# {"symbol": "DPZ", "name": "Domino's Pizza Inc"},
	# {"symbol": "AKAM", "name": "Akamai Technologies, Inc."},
	# {"symbol": "RL", "name": "Ralph Lauren Corporation"},
	# {"symbol": "TXT", "name": "Textron Inc."},
	# {"symbol": "SWKS", "name": "Skyworks Solutions, Inc."},
	# {"symbol": "EVRG", "name": "Evergy, Inc."},
	# {"symbol": "EPAM", "name": "EPAM Systems, Inc."},
	# {"symbol": "DOC", "name": "Healthpeak Properties, Inc."},
	# {"symbol": "APTV", "name": "Aptiv PLC"},
	# {"symbol": "RVTY", "name": "Revvity, Inc."},
	# {"symbol": "AMCR", "name": "Amcor plc"},
	# {"symbol": "REG", "name": "Regency Centers Corporation"},
	# {"symbol": "POOL", "name": "Pool Corporation"},
	# {"symbol": "INCY", "name": "Incyte Corporation"},
	# {"symbol": "BXP", "name": "BXP, Inc."},
	# {"symbol": "KMX", "name": "CarMax Inc"},
	# {"symbol": "CAG", "name": "ConAgra Brands, Inc."},
	# {"symbol": "HST", "name": "Host Hotels & Resorts, Inc."},
	# {"symbol": "JKHY", "name": "Jack Henry & Associates, Inc."},
	# {"symbol": "SWK", "name": "Stanley Black & Decker, Inc."},
	# {"symbol": "DVA", "name": "DaVita Inc."},
	# {"symbol": "CPB", "name": "The Campbell's Company"},
	# {"symbol": "CHRW", "name": "C.H. Robinson Worldwide, Inc."},
	# {"symbol": "JNPR", "name": "Juniper Networks, Inc."},
	# {"symbol": "CPT", "name": "Camden Property Trust"},
	# {"symbol": "TAP", "name": "Molson Coors Beverage Company"},
	# {"symbol": "NDSN", "name": "Nordson Corporation"},
	# {"symbol": "PAYC", "name": "Paycom Software, Inc."},
	# {"symbol": "UHS", "name": "Universal Health Services, Inc."},
	# {"symbol": "NCLH", "name": "Norwegian Cruise Line Holdings "},
	# {"symbol": "DAY", "name": "Dayforce, Inc."},
	# {"symbol": "SJM", "name": "The J.M. Smucker Company"},
	# {"symbol": "TECH", "name": "Bio-Techne Corp"},
	# {"symbol": "SOLV", "name": "Solventum Corporation"},
	# {"symbol": "ALLE", "name": "Allegion plc"},
	# {"symbol": "BG", "name": "Bunge Limited"},
	# {"symbol": "AIZ", "name": "Assurant, Inc."},
	# {"symbol": "IPG", "name": "Interpublic Group of Companies,"},
	# {"symbol": "BEN", "name": "Franklin Resources, Inc."},
	# {"symbol": "EMN", "name": "Eastman Chemical Company"},
	# {"symbol": "ALB", "name": "Albemarle Corporation"},
	# {"symbol": "MGM", "name": "MGM Resorts International"},
	# {"symbol": "AOS", "name": "A.O. Smith Corporation"},
	# {"symbol": "WYNN", "name": "Wynn Resorts, Limited"},
	# {"symbol": "PNW", "name": "Pinnacle West Capital Corporati"},
	# {"symbol": "ENPH", "name": "Enphase Energy, Inc."},
	# {"symbol": "LKQ", "name": "LKQ Corporation"},
	# {"symbol": "FRT", "name": "Federal Realty Investment Trust"},
	# {"symbol": "CRL", "name": "Charles River Laboratories Inte"},
	# {"symbol": "GNRC", "name": "Generac Holdlings Inc."},
	# {"symbol": "AES", "name": "The AES Corporation"},
	# {"symbol": "GL", "name": "Globe Life Inc."},
	# {"symbol": "LW", "name": "Lamb Weston Holdings, Inc."},
	# {"symbol": "HSIC", "name": "Henry Schein, Inc."},
	# {"symbol": "MKTX", "name": "MarketAxess Holdings, Inc."},
	# {"symbol": "MTCH", "name": "Match Group, Inc."},
	# {"symbol": "TFX", "name": "Teleflex Incorporated"},
	# {"symbol": "WBA", "name": "Walgreens Boots Alliance, Inc."},
	# {"symbol": "HAS", "name": "Hasbro, Inc."},
	# {"symbol": "IVZ", "name": "Invesco Ltd"},
	# {"symbol": "APA", "name": "APA Corporation"},
	# {"symbol": "MOS", "name": "Mosaic Company (The)"},
	# {"symbol": "PARA", "name": "Paramount Global"},
	# {"symbol": "MHK", "name": "Mohawk Industries, Inc."},
	# {"symbol": "CE", "name": "Celanese Corporation"},
	# {"symbol": "HII", "name": "Huntington Ingalls Industries, "},
	# {"symbol": "CZR", "name": "Caesars Entertainment, Inc."},
	# {"symbol": "BWA", "name": "BorgWarner Inc."},
	# {"symbol": "QRVO", "name": "Qorvo, Inc."},
	# {"symbol": "FMC", "name": "FMC Corporation"},
	# {"symbol": "AMTM", "name": "Amentum Holdings, Inc."},
]

DAILY_EXTRACT_CONFIG = [
    {
        "target_field": "previous_close",  # Stock price at end of previous trading session
        "selector_field": "[data-field='regularMarketPreviousClose']",
    },
	{
		"target_field": "open",  # Stock price at market open for current session
		"selector_field": "[data-field='regularMarketOpen']",
	},
 	{
		"target_field": "bid",  # Highest price a buyer will pay for 1 share (x 100 shares)
		"selector_field": "li:has(span:text('Bid')) span.value",
	},
	{
		"target_field": "ask",  # Lowest price a seller will sell 1 share (x 100 shares)
		"selector_field": "li:has(span:text('Ask')) span.value",
    },
	{
		"target_field": "day_range",  # Lowest and highest stock price for today
		"selector_field": "[data-field='regularMarketDayRange']",
    },
	{
		"target_field": "volume",  # Number of shares traded today
		"selector_field": "[data-field='regularMarketVolume']",
    },
	{
		"target_field": "avg_volume",  # Average daily traded volume over X period
		"selector_field": "[data-field='averageVolume']",
    },
	{
		"target_field": "intraday_market_cap",  # Total value of all oustanding shares
		"selector_field": "[data-field='marketCap']",
    },
	{
		"target_field": "beta",  # Stock volatility metric relative to market (S&P 500). 1 = moves with, < 1 = less volatile, > 1 more volatile
		"selector_field": "li:has(span:text('Beta (5Y Monthly)')) span.value",
	},
	{
		"target_field": "pe_ratio", # Price to earning ratio. How much investors are willing to pay for $1 of earnings.
		"selector_field": "li:has(span:text('PE Ratio (TTM)')) span.value",
	},
	{
		"target_field": "eps",  # Earnings per share. The company's profit per share
		"selector_field": "li:has(span:text('EPS (TTM)')) span.value",
	},
	{
		"target_field": "earnings_date",  # The expected date for next earnings report
		"selector_field": "li:has(span:text('Earnings Date (est.)')) span.value",
	},
	{
		"target_field": "forward_dividend_and_yield",  # The projected annual dividend (what a company pays a shareholder) per share and its percentage of the stock price
		"selector_field": "li:has(span:text('Forward Dividend & Yield')) span.value",
	},
	{
		"target_field": "ex_dividend_date",  # Cutoff date to receive next dividend
		"selector_field": "li:has(span:text('Ex-Dividend Date')) span.value",
	},
	{
		"target_field": "one_year_target_estimate",  # Estimated average stock price expected in next 12 months
		"selector_field": "li:has(span:text('1y Target Est')) span.value",
	},
]

# DIM_DATA_EXTRACT_CONFIG = [
# 	{
# 		"target_field": "company_name",
# 		"html_element_tag": "h1",
# 		"identifier_attribute": "class",
# 		"identifier_value": "yf-xxbei9",
# 		"is_data_value": True
# 	},
# 	{
# 		"target_field": "company_address",
# 		"html_element_tag": "div",
# 		"identifier_attribute": "class",
# 		"identifier_value": "address yf-wxp4ja",
# 		"is_data_value": True
# 	},
# 	{
# 		"target_field": "company_phone_number",
# 		"html_element_tag": "a",
# 		"identifier_attribute": "aria-label",
# 		"identifier_value": "phone number",
# 		"is_data_value": True
# 	},
# 	{
# 		"target_field": "company_website",
# 		"html_element_tag": "a",
# 		"identifier_attribute": "aria-label",
# 		"identifier_value": "website link",
# 		"is_data_value": True
# 	},
# 	{
# 		"target_field": "company_sector",
# 		"html_element_tag": "dt",
# 		"text_class_name": "yf-wxp4ja",
# 		"text_class_filter": "Sector:",
# 		"sibling_html_element_value_tag": "dd",
# 		"sibling_html_element_value_class": None,
# 		"is_text_value": True,
# 		"is_nested_text_value": True
# 	},
# 	{
# 		"target_field": "company_industry",
# 		"html_element_tag": "dt",
# 		"text_class_name": "yf-wxp4ja",
# 		"text_class_filter": "Industry:",
# 		"sibling_html_element_value_tag": "a",
# 		"sibling_html_element_value_class": "subtle-link fin-size-large yf-17w8w6",
# 		"is_text_value": True,
# 		"is_nested_text_value": True
# 	},
# 	{
# 		"target_field": "company_full_time_employees",
# 		"html_element_tag": "dt",
# 		"text_class_name": "yf-wxp4ja",
# 		"text_class_filter": "Full Time Employees:",
# 		"sibling_html_element_value_tag": "dd",
# 		"sibling_html_element_value_class": None,
# 		"is_text_value": True,
# 		"is_nested_text_value": True
# 	},
# 	{
# 		"target_field": "company_description",
# 		"html_element_tag": "section",
# 		"identifier_attribute": "data-fieldid",
# 		"identifier_value": "description",
# 		"is_data_value": True
# 	},
# 	{
# 		"target_field": "company_corporate_governance_score",
# 		"html_element_tag": "section",
# 		"identifier_attribute": "data-fieldid",
# 		"identifier_value": "corporate-governance",
# 		"is_data_value": True
# 	}
# ]
