star:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('AIRFLOW_VAR_GCP_PROJECT_ID') }}"
      dataset: dbt
      location: us-west1
      threads: 1
